print("Drone installation program engaged")
sleep(1)
fs.makeDir("system/")
print("Created system directory")
sleep(1)

shell.run("pastebin","get","JWWq1JZF","bootup_sequence.lua")
fs.move("bootup_sequence.lua","system/bootup_sequence.lua")
sleep(1)
shell.run("pastebin","get","63jzXpZy","receiveCommand.lua")
fs.move("receiveCommand.lua","system/receiveCommand.lua")
sleep(1)
shell.run("pastebin","get","MypYjxrL","receiveFile.lua")
fs.move("receiveFile.lua","system/receiveFile.lua")
sleep(1)
shell.run("pastebin","get","hWurwqU5","turtleRemoteControl.lua")
fs.move("turtleRemoteControl.lua","system/turtleRemoteControl.lua")
sleep(1)
shell.run("pastebin","get","6c7zHh8r","utility.lua")
fs.move("utility.lua","system/utility.lua")
sleep(1)
shell.run("pastebin","get","WyCk7SVx","startup.lua")
print("Final phase of drone install, enter a name.")
print("Name: ")
local name = read()
shell.run("label","set",name)